# Generated by Django 4.2.11 on 2024-04-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
