# Generated by Django 4.2.11 on 2024-04-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_remove_profilepic_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePic',
            new_name='ProfilePicture',
        ),
    ]
