# Generated by Django 4.2.11 on 2024-04-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_profilepicture_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppimage', models.ImageField(upload_to='profile_images/')),
                ('userId', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
