# Generated by Django 4.2.11 on 2024-04-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0008_profileimage_delete_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='userId',
        ),
    ]
