# Generated by Django 4.2.11 on 2024-04-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0009_remove_profileimage_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='ppimage',
            new_name='profile_picture',
        ),
    ]
