# Generated by Django 4.2.11 on 2024-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0010_rename_ppimage_profileimage_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='userId',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
