# Generated by Django 4.2.11 on 2024-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0011_profileimage_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userId',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='userId',
            field=models.CharField(max_length=255),
        ),
    ]
