# Generated by Django 4.2.11 on 2024-05-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0013_product_dislikes_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislike_users',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='like_users',
            field=models.JSONField(default=list),
        ),
    ]
