# Generated by Django 4.2.11 on 2024-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0014_product_dislike_users_product_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
